version: '3.6'
# Deploys Spring Music app that has mandatory dependency on Docker Compose project found at:
# https://github.com/fabianlee/docker-mongodb
#
# usage:
# sudo docker-compose -f docker-compose-mongo.yml build
# sudo docker-compose -f docker-compose-mongo.yml up

services:

  my-springmusic:
    image: my-springmusic
    build: .
    ports:
      - 8080:8080
    environment:
      # explicit profile required so that datasource is recognized and non-local
      - SPRING_PROFILES_ACTIVE=mongodb,remote
      # standard spring data property
      - spring.data.mongodb.uri=mongodb://admin:admin@my-mongodb:27017/test
    volumes:
      - javatmp:/tmp
    networks:
      - docker-mongodb_mongo_net

volumes:
  # default dir /var/lib/docker/volumes
  javatmp:

networks:
  docker-mongodb_mongo_net:
    external: true

