name: Run build on push
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew-sample
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload JAR
        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
        uses: actions/upload-artifact@v2
        with:
          #Set artifact name
          name: artifact
          #From this path
          path: 'build/libs/spring-music.jar'
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Deploy in cf
        uses: rk-1988/reference-application-sample-log@main
        with: 
          API:      ${{ secrets.CF_API }}
          ORG:      ${{ secrets.CF_ORG }}
          SPACE:    ${{ secrets.CF_SPACE }}
          USERNAME: ${{ secrets.CF_USERNAME }}
          PASSWORD: ${{ secrets.CF_PASSWORD }}
          MANIFEST: manifest.yml
          VALIDATE: false  
